/*
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.codingshuttle.ecommerce.events;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

/** Event published after inventory has been successfully reduced. */
@org.apache.avro.specific.AvroGenerated
public class OrderConfirmedEvent extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 2233714613535223305L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"OrderConfirmedEvent\",\"namespace\":\"com.codingshuttle.ecommerce.events\",\"doc\":\"Event published after inventory has been successfully reduced.\",\"fields\":[{\"name\":\"items\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"OrderRequestItem\",\"doc\":\"Represents an individual product included in the confirmed order.\",\"fields\":[{\"name\":\"productId\",\"type\":\"long\"},{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"quantity\",\"type\":\"int\"}]}},\"doc\":\"Avro arrays require type=array and items to specify the type of each element. Here, each element is an OrderRequestItem record.\"},{\"name\":\"totalPrice\",\"type\":\"double\",\"doc\":\"Total price of all items in the confirmed order.\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<OrderConfirmedEvent> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<OrderConfirmedEvent> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<OrderConfirmedEvent> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<OrderConfirmedEvent> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<OrderConfirmedEvent> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this OrderConfirmedEvent to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a OrderConfirmedEvent from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a OrderConfirmedEvent instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static OrderConfirmedEvent fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** Avro arrays require type=array and items to specify the type of each element. Here, each element is an OrderRequestItem record. */
  private java.util.List<com.codingshuttle.ecommerce.events.OrderRequestItem> items;
  /** Total price of all items in the confirmed order. */
  private double totalPrice;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public OrderConfirmedEvent() {}

  /**
   * All-args constructor.
   * @param items Avro arrays require type=array and items to specify the type of each element. Here, each element is an OrderRequestItem record.
   * @param totalPrice Total price of all items in the confirmed order.
   */
  public OrderConfirmedEvent(java.util.List<com.codingshuttle.ecommerce.events.OrderRequestItem> items, java.lang.Double totalPrice) {
    this.items = items;
    this.totalPrice = totalPrice;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return items;
    case 1: return totalPrice;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: items = (java.util.List<com.codingshuttle.ecommerce.events.OrderRequestItem>)value$; break;
    case 1: totalPrice = (java.lang.Double)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'items' field.
   * @return Avro arrays require type=array and items to specify the type of each element. Here, each element is an OrderRequestItem record.
   */
  public java.util.List<com.codingshuttle.ecommerce.events.OrderRequestItem> getItems() {
    return items;
  }


  /**
   * Sets the value of the 'items' field.
   * Avro arrays require type=array and items to specify the type of each element. Here, each element is an OrderRequestItem record.
   * @param value the value to set.
   */
  public void setItems(java.util.List<com.codingshuttle.ecommerce.events.OrderRequestItem> value) {
    this.items = value;
  }

  /**
   * Gets the value of the 'totalPrice' field.
   * @return Total price of all items in the confirmed order.
   */
  public double getTotalPrice() {
    return totalPrice;
  }


  /**
   * Sets the value of the 'totalPrice' field.
   * Total price of all items in the confirmed order.
   * @param value the value to set.
   */
  public void setTotalPrice(double value) {
    this.totalPrice = value;
  }

  /**
   * Creates a new OrderConfirmedEvent RecordBuilder.
   * @return A new OrderConfirmedEvent RecordBuilder
   */
  public static com.codingshuttle.ecommerce.events.OrderConfirmedEvent.Builder newBuilder() {
    return new com.codingshuttle.ecommerce.events.OrderConfirmedEvent.Builder();
  }

  /**
   * Creates a new OrderConfirmedEvent RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new OrderConfirmedEvent RecordBuilder
   */
  public static com.codingshuttle.ecommerce.events.OrderConfirmedEvent.Builder newBuilder(com.codingshuttle.ecommerce.events.OrderConfirmedEvent.Builder other) {
    if (other == null) {
      return new com.codingshuttle.ecommerce.events.OrderConfirmedEvent.Builder();
    } else {
      return new com.codingshuttle.ecommerce.events.OrderConfirmedEvent.Builder(other);
    }
  }

  /**
   * Creates a new OrderConfirmedEvent RecordBuilder by copying an existing OrderConfirmedEvent instance.
   * @param other The existing instance to copy.
   * @return A new OrderConfirmedEvent RecordBuilder
   */
  public static com.codingshuttle.ecommerce.events.OrderConfirmedEvent.Builder newBuilder(com.codingshuttle.ecommerce.events.OrderConfirmedEvent other) {
    if (other == null) {
      return new com.codingshuttle.ecommerce.events.OrderConfirmedEvent.Builder();
    } else {
      return new com.codingshuttle.ecommerce.events.OrderConfirmedEvent.Builder(other);
    }
  }

  /**
   * RecordBuilder for OrderConfirmedEvent instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<OrderConfirmedEvent>
    implements org.apache.avro.data.RecordBuilder<OrderConfirmedEvent> {

    /** Avro arrays require type=array and items to specify the type of each element. Here, each element is an OrderRequestItem record. */
    private java.util.List<com.codingshuttle.ecommerce.events.OrderRequestItem> items;
    /** Total price of all items in the confirmed order. */
    private double totalPrice;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.codingshuttle.ecommerce.events.OrderConfirmedEvent.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.items)) {
        this.items = data().deepCopy(fields()[0].schema(), other.items);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.totalPrice)) {
        this.totalPrice = data().deepCopy(fields()[1].schema(), other.totalPrice);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
    }

    /**
     * Creates a Builder by copying an existing OrderConfirmedEvent instance
     * @param other The existing instance to copy.
     */
    private Builder(com.codingshuttle.ecommerce.events.OrderConfirmedEvent other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.items)) {
        this.items = data().deepCopy(fields()[0].schema(), other.items);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.totalPrice)) {
        this.totalPrice = data().deepCopy(fields()[1].schema(), other.totalPrice);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'items' field.
      * Avro arrays require type=array and items to specify the type of each element. Here, each element is an OrderRequestItem record.
      * @return The value.
      */
    public java.util.List<com.codingshuttle.ecommerce.events.OrderRequestItem> getItems() {
      return items;
    }


    /**
      * Sets the value of the 'items' field.
      * Avro arrays require type=array and items to specify the type of each element. Here, each element is an OrderRequestItem record.
      * @param value The value of 'items'.
      * @return This builder.
      */
    public com.codingshuttle.ecommerce.events.OrderConfirmedEvent.Builder setItems(java.util.List<com.codingshuttle.ecommerce.events.OrderRequestItem> value) {
      validate(fields()[0], value);
      this.items = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'items' field has been set.
      * Avro arrays require type=array and items to specify the type of each element. Here, each element is an OrderRequestItem record.
      * @return True if the 'items' field has been set, false otherwise.
      */
    public boolean hasItems() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'items' field.
      * Avro arrays require type=array and items to specify the type of each element. Here, each element is an OrderRequestItem record.
      * @return This builder.
      */
    public com.codingshuttle.ecommerce.events.OrderConfirmedEvent.Builder clearItems() {
      items = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'totalPrice' field.
      * Total price of all items in the confirmed order.
      * @return The value.
      */
    public double getTotalPrice() {
      return totalPrice;
    }


    /**
      * Sets the value of the 'totalPrice' field.
      * Total price of all items in the confirmed order.
      * @param value The value of 'totalPrice'.
      * @return This builder.
      */
    public com.codingshuttle.ecommerce.events.OrderConfirmedEvent.Builder setTotalPrice(double value) {
      validate(fields()[1], value);
      this.totalPrice = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'totalPrice' field has been set.
      * Total price of all items in the confirmed order.
      * @return True if the 'totalPrice' field has been set, false otherwise.
      */
    public boolean hasTotalPrice() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'totalPrice' field.
      * Total price of all items in the confirmed order.
      * @return This builder.
      */
    public com.codingshuttle.ecommerce.events.OrderConfirmedEvent.Builder clearTotalPrice() {
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public OrderConfirmedEvent build() {
      try {
        OrderConfirmedEvent record = new OrderConfirmedEvent();
        record.items = fieldSetFlags()[0] ? this.items : (java.util.List<com.codingshuttle.ecommerce.events.OrderRequestItem>) defaultValue(fields()[0]);
        record.totalPrice = fieldSetFlags()[1] ? this.totalPrice : (java.lang.Double) defaultValue(fields()[1]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<OrderConfirmedEvent>
    WRITER$ = (org.apache.avro.io.DatumWriter<OrderConfirmedEvent>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<OrderConfirmedEvent>
    READER$ = (org.apache.avro.io.DatumReader<OrderConfirmedEvent>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    long size0 = this.items.size();
    out.writeArrayStart();
    out.setItemCount(size0);
    long actualSize0 = 0;
    for (com.codingshuttle.ecommerce.events.OrderRequestItem e0: this.items) {
      actualSize0++;
      out.startItem();
      e0.customEncode(out);
    }
    out.writeArrayEnd();
    if (actualSize0 != size0)
      throw new java.util.ConcurrentModificationException("Array-size written was " + size0 + ", but element count was " + actualSize0 + ".");

    out.writeDouble(this.totalPrice);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      long size0 = in.readArrayStart();
      java.util.List<com.codingshuttle.ecommerce.events.OrderRequestItem> a0 = this.items;
      if (a0 == null) {
        a0 = new SpecificData.Array<com.codingshuttle.ecommerce.events.OrderRequestItem>((int)size0, SCHEMA$.getField("items").schema());
        this.items = a0;
      } else a0.clear();
      SpecificData.Array<com.codingshuttle.ecommerce.events.OrderRequestItem> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<com.codingshuttle.ecommerce.events.OrderRequestItem>)a0 : null);
      for ( ; 0 < size0; size0 = in.arrayNext()) {
        for ( ; size0 != 0; size0--) {
          com.codingshuttle.ecommerce.events.OrderRequestItem e0 = (ga0 != null ? ga0.peek() : null);
          if (e0 == null) {
            e0 = new com.codingshuttle.ecommerce.events.OrderRequestItem();
          }
          e0.customDecode(in);
          a0.add(e0);
        }
      }

      this.totalPrice = in.readDouble();

    } else {
      for (int i = 0; i < 2; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          long size0 = in.readArrayStart();
          java.util.List<com.codingshuttle.ecommerce.events.OrderRequestItem> a0 = this.items;
          if (a0 == null) {
            a0 = new SpecificData.Array<com.codingshuttle.ecommerce.events.OrderRequestItem>((int)size0, SCHEMA$.getField("items").schema());
            this.items = a0;
          } else a0.clear();
          SpecificData.Array<com.codingshuttle.ecommerce.events.OrderRequestItem> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<com.codingshuttle.ecommerce.events.OrderRequestItem>)a0 : null);
          for ( ; 0 < size0; size0 = in.arrayNext()) {
            for ( ; size0 != 0; size0--) {
              com.codingshuttle.ecommerce.events.OrderRequestItem e0 = (ga0 != null ? ga0.peek() : null);
              if (e0 == null) {
                e0 = new com.codingshuttle.ecommerce.events.OrderRequestItem();
              }
              e0.customDecode(in);
              a0.add(e0);
            }
          }
          break;

        case 1:
          this.totalPrice = in.readDouble();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }

  @Override
  public int hashCode() {
    int result = 1;
    result = 31 * result + (items == null ? 0 : items.hashCode());
    result = 31 * result + Double.hashCode(totalPrice);
    return result;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (!(o instanceof OrderConfirmedEvent)) {
      return false;
    }
    OrderConfirmedEvent other = (OrderConfirmedEvent) o;
    if (!java.util.Objects.equals(this.items, other.items)) {
      return false;
    }
    if (this.totalPrice != other.totalPrice) {
      return false;
    }
    return true;
  }
}










