input {
  file {
    path => "/Users/shubhgaur/Documents/Docker/eCommerce/logs/*/application-*.log"
    start_position => "beginning"
  }
}

output {
  elasticsearch {
    hosts => ["http://localhost:9200"]
    index => "ecommerce-spring-boot-logs-%{+YYYY.MM.dd}"
    ssl_certificate_validation => false
    user => "elastic"
    password => "${ELASTIC_PASSWORD}" # passed as an environment variable for logstash container
  }

  stdout {
    codec => rubydebug
  }

}