server.port: 8888

spring.application.name: config-server
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/shubhgaur37/ecommerce-config-server
          username: shubhgaur37
          password: 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
          default-label: main






